- name: Include vars
  include_vars: common.yml

- name: Add Python 3.7 PPA
  apt_repository:
    repo: ppa:deadsnakes/ppa
  become: true

- name: Install debs
  apt:
    name: "{{ debs }}"
    update_cache: yes
  become: yes

- name: Download boost
  get_url:
    url: "https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz"
    dest: "{{ workspace }}/boost_1_67_0.tar.gz"

- name: Expand boost
  unarchive:
    src: "{{ workspace }}/boost_1_67_0.tar.gz"
    dest: "/usr/local/include"
    copy: no
    creates: "/usr/local/include/boost_1_67_0/bootstrap.sh"
  become: yes

- name: Download mbedtls-everest
  get_url:
    url: https://github.com/ARMmbed/mbedtls/archive/{{ mbedtls_src }}
    dest: "{{ workspace }}/{{ mbedtls_src }}"
  become: true

- name: Remove existing mbedtls checkout
  file:
    path: "{{ workspace }}/mbedtls-{{ mbedtls_dir }}"
    state: absent

- name: Expand mbedtls
  unarchive:
    src: "{{ workspace }}/{{ mbedtls_src }}"
    dest: "{{ workspace }}"
    copy: no
    creates: "{{ workspace }}/mbedtls-{{ mbedtls_dir }}/CMakeLists.txt"

- name: Make mbedtls build dir
  file:
    path: "{{ workspace }}/mbedtls-{{ mbedtls_dir }}/build"
    state: directory

- name: Build mbedtls
  shell: |
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
    make -j4
  args:
    chdir: "{{ workspace }}/mbedtls-{{ mbedtls_dir }}/build"

- name: Install mbedtls
  command: make install
  args:
    chdir: "{{ workspace }}/mbedtls-{{ mbedtls_dir }}/build"
  become: true