trigger:
  batch: true
  branches:
    include:
      - "master"
      - "ci/*"
  paths:
    exclude:
      - 'README.md'
      - 'CCF-TECHNICAL-REPORT.pdf'
      - 'Dockerfile'
      - 'Doxyfile'
      - 'THIRD_PARTY_NOTICES.txt'
      - 'getting_started/'
      - 'sphinx/'
      - '.github/'
      - '.azure-pipelines-gh-pages.yml'
      - 'LICENSE'

pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'
    exclude:
      - 'README.md'
      - 'CCF-TECHNICAL-REPORT.pdf'
      - 'Dockerfile'
      - 'Doxyfile'
      - 'THIRD_PARTY_NOTICES.txt'
      - 'getting_started/'
      - 'sphinx/'
      - '.github/'
      - '.azure-pipelines-gh-pages.yml'
      - 'LICENSE'

schedules:
- cron: "0 3 * * Mon-Fri"
  displayName: Daily morning build
  branches:
    include:
    - master
  always: true

jobs:
- job: ACC_1804_SGX_build
  pool: Ubuntu-1804-DC4s
  container:
    image: ccfciteam/ccf-ci-18.04-oe-0.6-sgx-no-mitigation:latest
    # --publish-all enables end-to-end tests to communicate over ports
    # --device /dev/sgx:/dev/sgx makes sgx available to the container
    options: --publish-all --device /dev/sgx:/dev/sgx
  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: .azure-pipelines-templates/build.yml
      parameters:
        cmake_args: '-DBUILD_SMALLBANK=OFF'
    - template: .azure-pipelines-templates/publish_build.yml
      parameters:
        artifact_name: build_results

- job: ACC_1804_SGX_quick_tests
  pool: Ubuntu-1804-DC4s
  container:
    image: ccfciteam/ccf-ci-18.04-oe-0.6-sgx-no-mitigation:latest
    # --publish-all enables end-to-end tests to communicate over ports
    # --device /dev/sgx:/dev/sgx makes sgx available to the container
    options: --publish-all --device /dev/sgx:/dev/sgx
  dependsOn:
    - ACC_1804_SGX_build
  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: .azure-pipelines-templates/download_build.yml
      parameters:
        artifact_name: build_results
    - template: .azure-pipelines-templates/test.yml
      parameters:
        ctest_filter: '-LE "perf|end_to_end"'
        suite_name_suffix: ' SGX quick tests'

- job: ACC_1804_SGX_e2e_tests_A
  pool: Ubuntu-1804-DC4s
  container:
    image: ccfciteam/ccf-ci-18.04-oe-0.6-sgx-no-mitigation:latest
    # --publish-all enables end-to-end tests to communicate over ports
    # --device /dev/sgx:/dev/sgx makes sgx available to the container
    options: --publish-all --device /dev/sgx:/dev/sgx
  dependsOn:
    - ACC_1804_SGX_build
  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: .azure-pipelines-templates/download_build.yml
      parameters:
        artifact_name: build_results
    - template: .azure-pipelines-templates/test.yml
      parameters:
        ctest_filter: '-L end_to_end -I 0,,2'
        suite_name_suffix: ' SGX end to end tests A'

- job: ACC_1804_SGX_e2e_tests_B
  pool: Ubuntu-1804-DC4s
  container:
    image: ccfciteam/ccf-ci-18.04-oe-0.6-sgx-no-mitigation:latest
    # --publish-all enables end-to-end tests to communicate over ports
    # --device /dev/sgx:/dev/sgx makes sgx available to the container
    options: --publish-all --device /dev/sgx:/dev/sgx
  dependsOn:
    - ACC_1804_SGX_build
  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: .azure-pipelines-templates/download_build.yml
      parameters:
        artifact_name: build_results
    - template: .azure-pipelines-templates/test.yml
      parameters:
        ctest_filter: '-L end_to_end -I 1,,2'
        suite_name_suffix: ' SGX end to end tests B'

- job: ACC_1804_SGX_perf_build
  pool: Ubuntu-1804-DC4s
  container:
    image: ccfciteam/ccf-ci-18.04-oe-0.6-sgx-no-mitigation:latest
    # --publish-all enables end-to-end tests to communicate over ports
    # --device /dev/sgx:/dev/sgx makes sgx available to the container
    options: --publish-all --device /dev/sgx:/dev/sgx
  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: .azure-pipelines-templates/build.yml
      parameters:
        cmake_args: '-DBUILD_SMALLBANK=ON -DSERVICE_IDENTITY_CURVE_CHOICE=secp256k1_bitcoin'
    - template: .azure-pipelines-templates/publish_build.yml
      parameters:
        artifact_name: perf_build_results

- job: ACC_1804_SGX_perf_tests
  pool: Ubuntu-1804-DC4s
  container:
    image: ccfciteam/ccf-ci-18.04-oe-0.6-sgx-no-mitigation:latest
    # --publish-all enables end-to-end tests to communicate over ports
    # --device /dev/sgx:/dev/sgx makes sgx available to the container
    options: --publish-all --device /dev/sgx:/dev/sgx -v /mnt/build:/__w/
  dependsOn:
    - ACC_1804_SGX_perf_build
  steps:
    - checkout: self
      clean: true
      submodules: true
    - template: .azure-pipelines-templates/download_build.yml
      parameters:
        artifact_name: perf_build_results
    - template: .azure-pipelines-templates/test.yml
      parameters:
        suite_name_suffix: ' SGX Performance'
        ctest_filter: '-L perf'
    - template: .azure-pipelines-templates/push_perf_data.yml