trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    exclude:
      - 'README.md'
      - 'CCF-TECHNICAL-REPORT.pdf'
      - 'Doxyfile'
      - 'THIRD_PARTY_NOTICES.txt'
      - 'getting_started/'
      - 'sphinx/'
      - '.github/'
      - '.azure-pipelines-gh-pages.yml'
      - 'LICENSE'

pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'
    exclude:
      - 'README.md'
      - 'CCF-TECHNICAL-REPORT.pdf'
      - 'Doxyfile'
      - 'THIRD_PARTY_NOTICES.txt'
      - 'getting_started/'
      - 'sphinx/'
      - '.github/'
      - '.azure-pipelines-gh-pages.yml'
      - 'LICENSE'

schedules:
- cron: "0 3 * * Mon-Fri"
  displayName: Daily morning build
  branches:
    include:
    - master
  always: true

resources:
  containers:
    - container: nosgx
      image: ccfciteam/ccf-ci-18.04-oe-0.7.0-sgx:latest
      options: --publish-all --cap-add SYS_PTRACE -v /dev/shm:/ccache

    - container: sgx
      image: ccfciteam/ccf-ci-18.04-oe-0.7.0-sgx:latest
      options: --publish-all --device /dev/sgx:/dev/sgx -v /dev/shm:/ccache

jobs:
- template: .azure-pipelines-templates/matrix.yml
