trigger:
  branches:
    include:
      - "master"

jobs:
- job: build_and_publish_docs
  pool: Ubuntu-1804-SGX-Azure
  steps:
    - checkout: self
      clean: true
      submodules: true

    - script: doxygen 
      displayName: Doxgen

    - script: |
        python3.7 -m venv env
        source env/bin/activate
        pip install -U -r requirements.txt
        make html
      displayName: Sphinx
      workingDirectory: sphinx

- job: ACC_1804_virtual_SAN_build
  pool: Ubuntu-1804-SGX-Azure
  steps:
    - template: .vsts-ci-templates/build_and_test.yml
      parameters:
        cmake_args: '-DVIRTUAL_ONLY=ON -DSAN=ON'
        suite_name_suffix: ' Virtual SAN'
