workspace: "/tmp/"
debs:
  - apt-transport-https
  - ninja-build
  - libuv1-dev
  - libc++-8-dev
  - libc++abi-8-dev
  - python3.7-dev
  - python3.7-venv
  - llvm-8
  - clang-8
  - expect
  - xsltproc
  - git
  - libcurl4-openssl-dev
mbedtls_ver: "2.16.2"
mbedtls_dir: "mbedtls-{{ mbedtls_ver }}"
mbedtls_src: "{{ mbedtls_dir }}.tar.gz"