workspace: "/tmp/"
debs:
  - ninja-build
  - libuv1-dev
  - libc++-7-dev
  - libc++abi-7-dev
  - python3.7-dev
  - python3.7-venv
  - llvm-7
  - expect
  - xsltproc
  - git
  - libcurl4-openssl-dev
mbedtls_ver: "2.16.2"
mbedtls_dir: "mbedtls-{{ mbedtls_ver }}"
mbedtls_src: "{{ mbedtls_dir }}.tar.gz"