workspace: "/tmp/"
oe_ver: "0.7.0"
oe_src: "oe-{{ oe_ver }}.tar.gz"
oe_url: "https://github.com/openenclave/openenclave/tarball/e529c2e6f17c19f8010082b4ab3d95dcac4aa5f4"
oe_prefix: "/opt/openenclave"
