workspace: "/tmp/"
oe_ver: "0.8.0-rc1"
oe_src: "oe-{{ oe_ver }}.tar.gz"
oe_url: "https://github.com/openenclave/openenclave/tarball/8ea614e8bec78f50de2aa9de556e3b431baa62ad"
oe_prefix: "/opt/openenclave"
