workspace: "/tmp/"
oe_ver: "0.7.0-rc1"
oe_src: "oe-{{ oe_ver }}.tar.gz"
oe_url: "https://github.com/openenclave/openenclave/tarball/dab09ecd3d428c571b115621d68e2c9f995572e2"
oe_prefix: "/opt/openenclave"
