version: 2
jobs:
  build:
    resource_class: large

    docker:
      - image: ccfciteam/ccf-ci-18.04:latest

    steps:
      - checkout

      - run:
          name: Shell Check
          command: find . -regex ".*\.sh$" | xargs shellcheck -s bash -e SC2044,SC2002,SC1091

      - run:
          name: Check copyright notices
          command: python3.7 notice-check.py

      - run:
          name: Check C++ code format
          command: ./check-format.sh src

      - run:
          name: Check Python code format
          command: |
            python3.7 -m venv env
            source env/bin/activate
            pip install black
            black --check sphinx/ tests/ notice-check.py

      - run:
          name: Make build directory
          command: mkdir build

      - run:
          name: CMake
          command: 'cmake -GNinja -DVIRTUAL_ONLY=ON ..'
          working_directory: build

      - run:
          name: Ninja
          command: ninja -j4
          working_directory: build

      - run:
          name: Run tests
          working_directory: build
          command: ./tests.sh -VV --timeout 240 --no-compress-output -T Test

      - run:
          name: Extract test results
          working_directory: build
          command: |
            mkdir -p test-results/junit
            xsltproc --stringparam suiteName "Virtual Build" ../tests/infra/ctest_to_junit.xslt Testing/*/Test.xml > test-results/junit/results.xml

      - store_test_results:
          path: build/test-results
