// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the Apache 2.0 License.
#pragma once

// FOREACH macro machinery for counting args

// -Wpedantic flags token pasting of __VA_ARGS__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgnu-zero-variadic-macro-arguments"

#define __FOR_JSON_COUNT_NN( \
  _0, \
  _1, \
  _2, \
  _3, \
  _4, \
  _5, \
  _6, \
  _7, \
  _8, \
  _9, \
  _10, \
  _11, \
  _12, \
  _13, \
  _14, \
  _15, \
  _16, \
  _17, \
  _18, \
  _19, \
  _20, \
  _21, \
  _22, \
  _23, \
  _24, \
  _25, \
  _26, \
  _27, \
  _28, \
  _29, \
  _30, \
  N, \
  ...) \
  _FOR_JSON_##N
#define _FOR_JSON_COUNT_NN_WITH_0(...) \
  __FOR_JSON_COUNT_NN( \
    __VA_ARGS__, \
    30, \
    29, \
    28, \
    27, \
    26, \
    25, \
    24, \
    23, \
    22, \
    21, \
    20, \
    19, \
    18, \
    17, \
    16, \
    15, \
    14, \
    13, \
    12, \
    11, \
    10, \
    9, \
    8, \
    7, \
    6, \
    5, \
    4, \
    3, \
    2, \
    1, \
    0)
#define _FOR_JSON_COUNT_NN(...) _FOR_JSON_COUNT_NN_WITH_0(DUMMY, ##__VA_ARGS__)

#define _FOR_JSON_0(POP_N) _FOR_JSON_0_##POP_N
#define _FOR_JSON_1(POP_N) _FOR_JSON_1_##POP_N
#define _FOR_JSON_2(POP_N) _FOR_JSON_2_##POP_N
#define _FOR_JSON_3(POP_N) _FOR_JSON_3_##POP_N
#define _FOR_JSON_4(POP_N) _FOR_JSON_4_##POP_N
#define _FOR_JSON_5(POP_N) _FOR_JSON_5_##POP_N
#define _FOR_JSON_6(POP_N) _FOR_JSON_6_##POP_N
#define _FOR_JSON_7(POP_N) _FOR_JSON_7_##POP_N
#define _FOR_JSON_8(POP_N) _FOR_JSON_8_##POP_N
#define _FOR_JSON_9(POP_N) _FOR_JSON_9_##POP_N
#define _FOR_JSON_10(POP_N) _FOR_JSON_10_##POP_N
#define _FOR_JSON_11(POP_N) _FOR_JSON_11_##POP_N
#define _FOR_JSON_12(POP_N) _FOR_JSON_12_##POP_N
#define _FOR_JSON_13(POP_N) _FOR_JSON_13_##POP_N
#define _FOR_JSON_14(POP_N) _FOR_JSON_14_##POP_N
#define _FOR_JSON_15(POP_N) _FOR_JSON_15_##POP_N
#define _FOR_JSON_16(POP_N) _FOR_JSON_16_##POP_N
#define _FOR_JSON_17(POP_N) _FOR_JSON_17_##POP_N
#define _FOR_JSON_18(POP_N) _FOR_JSON_18_##POP_N
#define _FOR_JSON_19(POP_N) _FOR_JSON_19_##POP_N
#define _FOR_JSON_20(POP_N) _FOR_JSON_20_##POP_N
#define _FOR_JSON_21(POP_N) _FOR_JSON_21_##POP_N
#define _FOR_JSON_22(POP_N) _FOR_JSON_22_##POP_N
#define _FOR_JSON_23(POP_N) _FOR_JSON_23_##POP_N
#define _FOR_JSON_24(POP_N) _FOR_JSON_24_##POP_N
#define _FOR_JSON_25(POP_N) _FOR_JSON_25_##POP_N
#define _FOR_JSON_26(POP_N) _FOR_JSON_26_##POP_N
#define _FOR_JSON_27(POP_N) _FOR_JSON_27_##POP_N
#define _FOR_JSON_28(POP_N) _FOR_JSON_28_##POP_N
#define _FOR_JSON_29(POP_N) _FOR_JSON_29_##POP_N
#define _FOR_JSON_30(POP_N) _FOR_JSON_30_##POP_N

// FOREACH macro machinery for forwarding to single arg macros
#define _FOR_JSON_0_POP1(FUNC, TYPE)
#define _FOR_JSON_1_POP1(FUNC, TYPE, ARG1) _FOR_JSON_FINAL(FUNC, TYPE, ARG1)
#define _FOR_JSON_2_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_1_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_3_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_2_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_4_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_3_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_5_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_4_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_6_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_5_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_7_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_6_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_8_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_7_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_9_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_8_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_10_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_9_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_11_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_10_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_12_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_11_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_13_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_12_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_14_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_13_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_15_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_14_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_16_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_15_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_17_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_16_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_18_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_17_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_19_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_18_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_20_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_19_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_21_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_20_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_22_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_21_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_23_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_22_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_24_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_23_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_25_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_24_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_26_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_25_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_27_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_26_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_28_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_27_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_29_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_28_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_30_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) \
  _FOR_JSON_29_POP1(FUNC, TYPE, ##__VA_ARGS__)

// FOREACH macro machinery for forwarding to double arg macros
#define _FOR_JSON_0_POP2(FUNC, TYPE)
#define _FOR_JSON_1_POP2(FUNC, TYPE, ARG1) INVALID_ODD_ARGS
#define _FOR_JSON_2_POP2(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_FINAL(FUNC, TYPE, ARG1, ARG2)
#define _FOR_JSON_3_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_4_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_2_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_5_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_6_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_4_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_7_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_8_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_6_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_9_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_10_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_8_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_11_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_12_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_10_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_13_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_14_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_12_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_15_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_16_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_14_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_17_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_18_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_16_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_19_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_20_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_18_POP2(FUNC, TYPE, ##__VA_ARGS__)

// Forwarders for macros produced by the machinery above
#define _FOR_JSON_NEXT(FUNC, ...) FUNC##_FOR_JSON_NEXT(__VA_ARGS__)
#define _FOR_JSON_FINAL(FUNC, ...) FUNC##_FOR_JSON_FINAL(__VA_ARGS__)

#pragma clang diagnostic pop
