// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the Apache 2.0 License.
#pragma once

// FOREACH macro machinery for counting args

// -Wpedantic flags token pasting of __VA_ARGS__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgnu-zero-variadic-macro-arguments"

#define __FOR_JSON_COUNT_NN( \
  _0, \
  _1, \
  _2, \
  _3, \
  _4, \
  _5, \
  _6, \
  _7, \
  _8, \
  _9, \
  _10, \
  _11, \
  _12, \
  _13, \
  _14, \
  _15, \
  _16, \
  _17, \
  _18, \
  _19, \
  _20, \
  _21, \
  _22, \
  _23, \
  _24, \
  _25, \
  _26, \
  _27, \
  _28, \
  _29, \
  _30, \
  _31, \
  _32, \
  _33, \
  _34, \
  _35, \
  _36, \
  _37, \
  _38, \
  _39, \
  _40, \
  _41, \
  _42, \
  _43, \
  _44, \
  _45, \
  _46, \
  _47, \
  _48, \
  _49, \
  _50, \
  _51, \
  _52, \
  _53, \
  _54, \
  _55, \
  _56, \
  _57, \
  _58, \
  _59, \
  _60, \
  _61, \
  _62, \
  _63, \
  _64, \
  _65, \
  _66, \
  _67, \
  _68, \
  _69, \
  _70, \
  _71, \
  _72, \
  _73, \
  _74, \
  _75, \
  _76, \
  _77, \
  _78, \
  _79, \
  _80, \
  _81, \
  _82, \
  _83, \
  _84, \
  _85, \
  _86, \
  _87, \
  _88, \
  _89, \
  _90, \
  N, \
  ...) \
  _FOR_JSON_##N
#define _FOR_JSON_COUNT_NN_WITH_0(...) \
  __FOR_JSON_COUNT_NN( \
    __VA_ARGS__, \
    90, \
    89, \
    88, \
    87, \
    86, \
    85, \
    84, \
    83, \
    82, \
    81, \
    80, \
    79, \
    78, \
    77, \
    76, \
    75, \
    74, \
    73, \
    72, \
    71, \
    70, \
    69, \
    68, \
    67, \
    66, \
    65, \
    64, \
    63, \
    62, \
    61, \
    60, \
    59, \
    58, \
    57, \
    56, \
    55, \
    54, \
    53, \
    52, \
    51, \
    50, \
    49, \
    48, \
    47, \
    46, \
    45, \
    44, \
    43, \
    42, \
    41, \
    40, \
    39, \
    38, \
    37, \
    36, \
    35, \
    34, \
    33, \
    32, \
    31, \
    30, \
    29, \
    28, \
    27, \
    26, \
    25, \
    24, \
    23, \
    22, \
    21, \
    20, \
    19, \
    18, \
    17, \
    16, \
    15, \
    14, \
    13, \
    12, \
    11, \
    10, \
    9, \
    8, \
    7, \
    6, \
    5, \
    4, \
    3, \
    2, \
    1, \
    0)
#define _FOR_JSON_COUNT_NN(...) _FOR_JSON_COUNT_NN_WITH_0(DUMMY, ##__VA_ARGS__)

#define _FOR_JSON_0(POP_N) _FOR_JSON_0_##POP_N
#define _FOR_JSON_1(POP_N) _FOR_JSON_1_##POP_N
#define _FOR_JSON_2(POP_N) _FOR_JSON_2_##POP_N
#define _FOR_JSON_3(POP_N) _FOR_JSON_3_##POP_N
#define _FOR_JSON_4(POP_N) _FOR_JSON_4_##POP_N
#define _FOR_JSON_5(POP_N) _FOR_JSON_5_##POP_N
#define _FOR_JSON_6(POP_N) _FOR_JSON_6_##POP_N
#define _FOR_JSON_7(POP_N) _FOR_JSON_7_##POP_N
#define _FOR_JSON_8(POP_N) _FOR_JSON_8_##POP_N
#define _FOR_JSON_9(POP_N) _FOR_JSON_9_##POP_N
#define _FOR_JSON_10(POP_N) _FOR_JSON_10_##POP_N
#define _FOR_JSON_11(POP_N) _FOR_JSON_11_##POP_N
#define _FOR_JSON_12(POP_N) _FOR_JSON_12_##POP_N
#define _FOR_JSON_13(POP_N) _FOR_JSON_13_##POP_N
#define _FOR_JSON_14(POP_N) _FOR_JSON_14_##POP_N
#define _FOR_JSON_15(POP_N) _FOR_JSON_15_##POP_N
#define _FOR_JSON_16(POP_N) _FOR_JSON_16_##POP_N
#define _FOR_JSON_17(POP_N) _FOR_JSON_17_##POP_N
#define _FOR_JSON_18(POP_N) _FOR_JSON_18_##POP_N
#define _FOR_JSON_19(POP_N) _FOR_JSON_19_##POP_N
#define _FOR_JSON_20(POP_N) _FOR_JSON_20_##POP_N
#define _FOR_JSON_21(POP_N) _FOR_JSON_21_##POP_N
#define _FOR_JSON_22(POP_N) _FOR_JSON_22_##POP_N
#define _FOR_JSON_23(POP_N) _FOR_JSON_23_##POP_N
#define _FOR_JSON_24(POP_N) _FOR_JSON_24_##POP_N
#define _FOR_JSON_25(POP_N) _FOR_JSON_25_##POP_N
#define _FOR_JSON_26(POP_N) _FOR_JSON_26_##POP_N
#define _FOR_JSON_27(POP_N) _FOR_JSON_27_##POP_N
#define _FOR_JSON_28(POP_N) _FOR_JSON_28_##POP_N
#define _FOR_JSON_29(POP_N) _FOR_JSON_29_##POP_N
#define _FOR_JSON_30(POP_N) _FOR_JSON_30_##POP_N
#define _FOR_JSON_31(POP_N) _FOR_JSON_31_##POP_N
#define _FOR_JSON_32(POP_N) _FOR_JSON_32_##POP_N
#define _FOR_JSON_33(POP_N) _FOR_JSON_33_##POP_N
#define _FOR_JSON_34(POP_N) _FOR_JSON_34_##POP_N
#define _FOR_JSON_35(POP_N) _FOR_JSON_35_##POP_N
#define _FOR_JSON_36(POP_N) _FOR_JSON_36_##POP_N
#define _FOR_JSON_37(POP_N) _FOR_JSON_37_##POP_N
#define _FOR_JSON_38(POP_N) _FOR_JSON_38_##POP_N
#define _FOR_JSON_39(POP_N) _FOR_JSON_39_##POP_N
#define _FOR_JSON_40(POP_N) _FOR_JSON_40_##POP_N
#define _FOR_JSON_41(POP_N) _FOR_JSON_41_##POP_N
#define _FOR_JSON_42(POP_N) _FOR_JSON_42_##POP_N
#define _FOR_JSON_43(POP_N) _FOR_JSON_43_##POP_N
#define _FOR_JSON_44(POP_N) _FOR_JSON_44_##POP_N
#define _FOR_JSON_45(POP_N) _FOR_JSON_45_##POP_N
#define _FOR_JSON_46(POP_N) _FOR_JSON_46_##POP_N
#define _FOR_JSON_47(POP_N) _FOR_JSON_47_##POP_N
#define _FOR_JSON_48(POP_N) _FOR_JSON_48_##POP_N
#define _FOR_JSON_49(POP_N) _FOR_JSON_49_##POP_N
#define _FOR_JSON_50(POP_N) _FOR_JSON_50_##POP_N
#define _FOR_JSON_51(POP_N) _FOR_JSON_51_##POP_N
#define _FOR_JSON_52(POP_N) _FOR_JSON_52_##POP_N
#define _FOR_JSON_53(POP_N) _FOR_JSON_53_##POP_N
#define _FOR_JSON_54(POP_N) _FOR_JSON_54_##POP_N
#define _FOR_JSON_55(POP_N) _FOR_JSON_55_##POP_N
#define _FOR_JSON_56(POP_N) _FOR_JSON_56_##POP_N
#define _FOR_JSON_57(POP_N) _FOR_JSON_57_##POP_N
#define _FOR_JSON_58(POP_N) _FOR_JSON_58_##POP_N
#define _FOR_JSON_59(POP_N) _FOR_JSON_59_##POP_N
#define _FOR_JSON_60(POP_N) _FOR_JSON_60_##POP_N
#define _FOR_JSON_61(POP_N) _FOR_JSON_61_##POP_N
#define _FOR_JSON_62(POP_N) _FOR_JSON_62_##POP_N
#define _FOR_JSON_63(POP_N) _FOR_JSON_63_##POP_N
#define _FOR_JSON_64(POP_N) _FOR_JSON_64_##POP_N
#define _FOR_JSON_65(POP_N) _FOR_JSON_65_##POP_N
#define _FOR_JSON_66(POP_N) _FOR_JSON_66_##POP_N
#define _FOR_JSON_67(POP_N) _FOR_JSON_67_##POP_N
#define _FOR_JSON_68(POP_N) _FOR_JSON_68_##POP_N
#define _FOR_JSON_69(POP_N) _FOR_JSON_69_##POP_N
#define _FOR_JSON_70(POP_N) _FOR_JSON_70_##POP_N
#define _FOR_JSON_71(POP_N) _FOR_JSON_71_##POP_N
#define _FOR_JSON_72(POP_N) _FOR_JSON_72_##POP_N
#define _FOR_JSON_73(POP_N) _FOR_JSON_73_##POP_N
#define _FOR_JSON_74(POP_N) _FOR_JSON_74_##POP_N
#define _FOR_JSON_75(POP_N) _FOR_JSON_75_##POP_N
#define _FOR_JSON_76(POP_N) _FOR_JSON_76_##POP_N
#define _FOR_JSON_77(POP_N) _FOR_JSON_77_##POP_N
#define _FOR_JSON_78(POP_N) _FOR_JSON_78_##POP_N
#define _FOR_JSON_79(POP_N) _FOR_JSON_79_##POP_N
#define _FOR_JSON_80(POP_N) _FOR_JSON_80_##POP_N
#define _FOR_JSON_81(POP_N) _FOR_JSON_81_##POP_N
#define _FOR_JSON_82(POP_N) _FOR_JSON_82_##POP_N
#define _FOR_JSON_83(POP_N) _FOR_JSON_83_##POP_N
#define _FOR_JSON_84(POP_N) _FOR_JSON_84_##POP_N
#define _FOR_JSON_85(POP_N) _FOR_JSON_85_##POP_N
#define _FOR_JSON_86(POP_N) _FOR_JSON_86_##POP_N
#define _FOR_JSON_87(POP_N) _FOR_JSON_87_##POP_N
#define _FOR_JSON_88(POP_N) _FOR_JSON_88_##POP_N
#define _FOR_JSON_89(POP_N) _FOR_JSON_89_##POP_N
#define _FOR_JSON_90(POP_N) _FOR_JSON_90_##POP_N

// FOREACH macro machinery for forwarding to single arg macros
#define _FOR_JSON_0_POP1(FUNC, TYPE)
#define _FOR_JSON_1_POP1(FUNC, TYPE, ARG1) _FOR_JSON_FINAL(FUNC, TYPE, ARG1)
#define _FOR_JSON_2_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_1_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_3_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_2_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_4_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_3_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_5_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_4_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_6_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_5_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_7_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_6_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_8_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_7_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_9_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_8_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_10_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_9_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_11_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_10_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_12_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_11_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_13_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_12_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_14_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_13_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_15_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_14_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_16_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_15_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_17_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_16_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_18_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_17_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_19_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_18_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_20_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_19_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_21_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_20_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_22_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_21_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_23_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_22_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_24_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_23_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_25_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_24_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_26_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_25_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_27_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_26_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_28_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_27_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_29_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_28_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_30_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_29_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_31_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_30_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_32_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_31_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_33_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_32_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_34_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_33_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_35_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_34_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_36_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_35_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_37_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_36_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_38_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_37_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_39_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_38_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_40_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_39_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_41_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_40_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_42_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_41_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_43_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_42_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_44_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_43_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_45_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_44_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_46_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_45_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_47_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_46_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_48_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_47_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_49_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_48_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_50_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_49_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_51_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_50_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_52_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_51_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_53_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_52_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_54_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_53_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_55_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_54_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_56_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_55_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_57_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_56_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_58_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_57_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_59_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_58_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_60_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_59_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_61_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_60_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_62_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_61_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_63_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_62_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_64_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_63_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_65_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_64_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_66_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_65_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_67_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_66_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_68_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_67_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_69_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_68_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_70_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_69_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_71_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_70_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_72_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_71_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_73_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_72_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_74_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_73_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_75_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_74_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_76_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_75_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_77_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_76_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_78_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_77_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_79_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_78_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_80_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_79_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_81_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_80_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_82_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_81_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_83_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_82_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_84_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_83_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_85_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_84_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_86_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_85_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_87_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_86_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_88_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_87_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_89_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_88_POP1(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_90_POP1(FUNC, TYPE, ARG1, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1) _FOR_JSON_89_POP1(FUNC, TYPE, ##__VA_ARGS__)

// FOREACH macro machinery for forwarding to double arg macros
#define INVALID_ODD_ARGS \
  static_assert( \
    false, \
    "This macro requires args in doubles, ie the total number of args must " \
    "be a multiple of 3");
#define _FOR_JSON_0_POP2(FUNC, TYPE)
#define _FOR_JSON_1_POP2(FUNC, TYPE, ARG1) INVALID_ODD_ARGS
#define _FOR_JSON_2_POP2(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_FINAL(FUNC, TYPE, ARG1, ARG2)
#define _FOR_JSON_3_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_4_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_2_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_5_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_6_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_4_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_7_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_8_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_6_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_9_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_10_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_8_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_11_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_12_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_10_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_13_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_14_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_12_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_15_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_16_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_14_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_17_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_18_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_16_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_19_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_20_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_18_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_21_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_22_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_20_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_23_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_24_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_22_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_25_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_26_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_24_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_27_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_28_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_26_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_29_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_30_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_28_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_31_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_32_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_30_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_33_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_34_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_32_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_35_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_36_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_34_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_37_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_38_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_36_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_39_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_40_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_38_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_41_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_42_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_40_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_43_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_44_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_42_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_45_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_46_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_44_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_47_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_48_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_46_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_49_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_50_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_48_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_51_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_52_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_50_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_53_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_54_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_52_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_55_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_56_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_54_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_57_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_58_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_56_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_59_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_60_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_58_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_61_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_62_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_60_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_63_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_64_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_62_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_65_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_66_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_64_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_67_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_68_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_66_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_69_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_70_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_68_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_71_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_72_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_70_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_73_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_74_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_72_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_75_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_76_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_74_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_77_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_78_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_76_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_79_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_80_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_78_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_81_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_82_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_80_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_83_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_84_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_82_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_85_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_86_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_84_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_87_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_88_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_86_POP2(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_89_POP2(FUNC, TYPE, ARG1, ARG2, ...) INVALID_ODD_ARGS
#define _FOR_JSON_90_POP2(FUNC, TYPE, ARG1, ARG2, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2) \
  _FOR_JSON_88_POP2(FUNC, TYPE, ##__VA_ARGS__)

// FOREACH macro machinery for forwarding to triple arg macros
#define INVALID_TRI_ARGS \
  static_assert( \
    false, \
    "This macro requires args in triples, ie the total number of args must " \
    "be a multiple of 3");
#define _FOR_JSON_0_POP3(FUNC, TYPE)
#define _FOR_JSON_1_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_2_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_3_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_0_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_4_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_5_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_6_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_3_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_7_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_8_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_9_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_6_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_10_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_11_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_12_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_9_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_13_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_14_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_15_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_12_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_16_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_17_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_18_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_15_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_19_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_20_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_21_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_18_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_22_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_23_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_24_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_21_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_25_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_26_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_27_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_24_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_28_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_29_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_30_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_27_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_31_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_32_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_33_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_30_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_34_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_35_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_36_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_33_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_37_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_38_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_39_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_36_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_40_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_41_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_42_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_39_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_43_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_44_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_45_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_42_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_46_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_47_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_48_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_45_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_49_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_50_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_51_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_48_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_52_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_53_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_54_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_51_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_55_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_56_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_57_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_54_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_58_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_59_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_60_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_57_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_61_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_62_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_63_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_60_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_64_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_65_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_66_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_63_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_67_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_68_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_69_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_66_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_70_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_71_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_72_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_69_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_73_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_74_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_75_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_72_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_76_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_77_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_78_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_75_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_79_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_80_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_81_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_78_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_82_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_83_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_84_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_81_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_85_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_86_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_87_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_84_POP3(FUNC, TYPE, ##__VA_ARGS__)
#define _FOR_JSON_88_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_89_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) INVALID_TRI_ARGS
#define _FOR_JSON_90_POP3(FUNC, TYPE, ARG1, ARG2, ARG3, ...) \
  _FOR_JSON_NEXT(FUNC, TYPE, ARG1, ARG2, ARG3) \
  _FOR_JSON_87_POP3(FUNC, TYPE, ##__VA_ARGS__)

// Forwarders for macros produced by the machinery above
#define _FOR_JSON_NEXT(FUNC, ...) FUNC##_FOR_JSON_NEXT(__VA_ARGS__)
#define _FOR_JSON_FINAL(FUNC, ...) FUNC##_FOR_JSON_FINAL(__VA_ARGS__)

#pragma clang diagnostic pop
