parameters:
  cmake_args: ''

steps:
- script: |
    cat /proc/cpuinfo
  displayName: /proc/cpuinfo
  condition: succeededOrFailed()

- script: |
    mkdir build
    cd build
    cmake -L -GNinja -DTARGET=sgx .. ${{ parameters.cmake_args }}
  displayName: CMake

- script: ninja
  displayName: Ninja
  workingDirectory: build
  env:
    CCACHE_DIR: /ccache
