jobs:
- job: Formatting_and_License_Checks
  displayName: 'Formatting and License Checks'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
      submodules: true

    - script: find . -regex ".*\.sh$" | xargs shellcheck -s bash -e SC2044,SC2002,SC1091
      displayName: 'Shell Check'

    - script: python3.7 notice-check.py
      displayName: 'Check CCF copyright notices'

    - script: python3.7 notice-check.py
      workingDirectory: ePBFT
      displayName: 'Check ePBFT copyright notices'

    - script: ./check-format.sh src samples ePBFT/src
      displayName: 'Check C++ code format'

    - script: |
        python3.7 -m venv env
        source env/bin/activate
        pip install black
        black --check sphinx/ tests/ notice-check.py
      displayName: 'Check Python code format'