jobs:
- job: ${{ parameters.job_name }}
  displayName: 'Formatting and License Checks'

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
      submodules: true

    - script: find . -type f -regex ".*\.sh$" | egrep -v "^./3rdparty/" | xargs shellcheck -s bash -e SC2044,SC2002,SC1091
      displayName: 'Shell Check'

    - script: ./check-format.sh src samples
      displayName: 'Check C++ code format'

    - script: python3.7 notice-check.py
      displayName: 'Check CCF copyright notices'

    - script: |
        python3.7 -m venv env
        source env/bin/activate
        pip install black
        black --check sphinx/ tests/ notice-check.py
      displayName: 'Check Python code format'

    - script: |
        source env/bin/activate
        pip install cmake_format
        cmake-format --check CMakeLists.txt $(find ./cmake ./samples ./src ./tests -name "*.cmake" | tr "\n" " ")
      displayName: 'Check CMake code format'