parameters:
  cmake_args: ''

steps:
- script: |
    cat /proc/cpuinfo
  displayName: /proc/cpuinfo
  condition: succeededOrFailed()

- script: |
    mkdir build
    cd build
    cmake -L -GNinja .. ${{ parameters.cmake_args }}
  displayName: CMake
