jobs:
- job: Build_${{ parameters.target }}_${{ parameters.suffix }}
  variables:
    skipComponentGovernanceDetection: true
  displayName: 'Build ${{ parameters.target }} ${{ parameters.suffix }}'
  dependsOn: ${{ parameters.depends_on }}

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - checkout: self
      clean: true
    - template: cmake.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'
    - template: ninja.yml
      parameters:
        cmake_args: '${{ parameters.cmake_args }}'
    - template: publish_build.yml
      parameters:
        artifact_name: ${{ parameters.artifact_name }}