parameters:	
  artifact_name: ''
  cmake_args: ''

steps:
- task: DownloadPipelineArtifact@1
  inputs:
    artifactName: ${{ parameters.artifact_name }}
    targetPath: $(Build.SourcesDirectory)/build

- script: |
    tar -xaf artifact.tar.gz
  displayName: Uncompress build artifact
  workingDirectory: build

- script: | 
    cmake -L ${{ parameters.cmake_args }} -GNinja ..
  displayName: Re-generate test metadata 
  workingDirectory: build