parameters:
  consensus: ['CFT', 'BFT']
  target: ['NoSGX', 'SGX']

  env:
    NoSGX:
      container: nosgx
      pool: Ubuntu-1804-D8s_v3
    SGX:
      container: sgx
      pool: Ubuntu-1804-DC4s
    NoSGX_SAN:
      container: nosgx
      pool: Ubuntu-1804-D16s_v3

  build:
    common:
      cmake_args: '-DCMAKE_C_COMPILER_LAUNCHER="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER="ccache"'
    NoSGX:
      cmake_args: '-DTARGET=virtual -DCOVERAGE=ON'
    SGX:
      cmake_args: ''
    BFT:
      cmake_args: '-DPBFT=ON'
    CFT:
      cmake_args: ''
    debug:
      cmake_args: '-DCMAKE_BUILD_TYPE=Debug -DBUILD_SMALLBANK=OFF'
    perf:
      cmake_args: '-DSERVICE_IDENTITY_CURVE_CHOICE=secp256k1_bitcoin'
    san:
      cmake_args: '-DSAN=ON'
    http:
      cmake_args: '-DHTTP=ON'

  test:
    NoSGX:
      ctest_args: '-LE "benchmark|perf|suite"'
    SGX:
      ctest_args: '-LE "benchmark|perf"'
    perf:
      ctest_args: '-L "benchmark|perf"'
    san:
      ctest_args: '-LE "benchmark|perf|suite"'

  static_check_job_name: 'Formatting_and_License_Checks'

  san_target: 'NoSGX'
  checks_target: 'NoSGX'

jobs:
  - template: checks.yml
    parameters:
      env: ${{ parameters.env[parameters.checks_target] }}
      job_name: ${{ parameters.static_check_job_name }}

  # Debug builds with code coverage, run all tests except performance
  - ${{ each target in parameters.target }}:
    - ${{ each consensus in parameters.consensus }}:
      - template: common.yml
        parameters:
          target: ${{ target }}
          consensus: ${{ consensus }}
          env: ${{ parameters.env[target] }}
          cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.debug.cmake_args }} ${{ parameters.build[target].cmake_args }} ${{ parameters.build[consensus].cmake_args }}'
          ctest_filter: '${{ parameters.test[target].ctest_args }}'
          suffix: ''
          depends_on: ${{ parameters.static_check_job_name }}

  # SAN builds (ASAN & UBSAN), run all tests except performance
  - ${{ each consensus in parameters.consensus }}:
    - template: common.yml
      parameters:
        target: ${{ parameters.san_target }}
        consensus: ${{ consensus }}
        env: '${{ parameters.env.NoSGX_SAN }}'
        cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.san.cmake_args }} ${{ parameters.build[parameters.san_target].cmake_args }} ${{ parameters.build[consensus].cmake_args }}'
        ctest_filter: '${{ parameters.test.san.ctest_args }}'
        suffix: 'SAN'
        depends_on: ${{ parameters.static_check_job_name }}

  # Optimised builds, only run performance tests
  - ${{ each consensus in parameters.consensus }}:
    - template: common.yml
      parameters:
        target: SGX
        consensus: ${{ consensus }}
        env: ${{ parameters.env.SGX }}
        cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.perf.cmake_args }} ${{ parameters.build.SGX.cmake_args }} ${{ parameters.build[consensus].cmake_args }}'
        ctest_filter: '${{ parameters.test.perf.ctest_args }}'
        suffix: 'Perf'
        depends_on: ${{ parameters.static_check_job_name }}

  # HTTP build (behind a toggle for now), only on NoSGX and CFT
  # TODO: Once large messages are supported with HTTP (e.g. quotes over join request), SGX should be run
  - template: common.yml
    parameters:
      target: NoSGX
      consensus: CFT
      env: ${{ parameters.env.NoSGX }}
      cmake_args: '${{ parameters.build.common.cmake_args }} ${{ parameters.build.debug.cmake_args }} ${{ parameters.build.NoSGX.cmake_args }} ${{ parameters.build.CFT.cmake_args }} ${{ parameters.build.http.cmake_args }}'
      ctest_filter: '${{ parameters.test.NoSGX.ctest_args }}'
      suffix: 'HTTP'
      depends_on: ${{ parameters.static_check_job_name }}
