parameters:
  artifact_name: ''

steps:
- script: |
    tar -cavf artifact.tar.gz cchost CTestTestfile.cmake json_schema genesisgenerator merkle_mem raft_driver tests.sh *_test *_bench *client *.so.signed
  displayName: Compress build artifact
  workingDirectory: build

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: ${{ parameters.artifact_name }}
    targetPath: build/artifact.tar.gz
