steps:
- script: |
    gzip -vk *_sent.csv *_recv.csv
    gzip -vk *_metrics.json
  displayName: Compress tx time metrics
  workingDirectory: build

- task: AzureCLI@1
  displayName: Push Performance Data
  inputs:
    azureConnectionType: connectedServiceNameARM
    azureSubscription: CCF-Persistence
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload -f perf_summary.csv -c perf -n $AGENT_NAME/${BUILD_SOURCEBRANCHNAME}_${BUILD_BUILDNUMBER}.csv --account-name ccfperf --subscription $(subscription)
      az storage blob upload-batch -d tx-times/$AGENT_NAME/${BUILD_SOURCEBRANCHNAME}_${BUILD_BUILDNUMBER} -s. --pattern "client_*_sent.csv.gz" --account-name ccfperf --subscription $(subscription)
      az storage blob upload-batch -d tx-times/$AGENT_NAME/${BUILD_SOURCEBRANCHNAME}_${BUILD_BUILDNUMBER} -s. --pattern "client_*_recv.csv.gz" --account-name ccfperf --subscription $(subscription)
      az storage blob upload-batch -d metrics/$AGENT_NAME/${BUILD_SOURCEBRANCHNAME}_${BUILD_BUILDNUMBER} -s. --pattern "*_metrics.json.gz" --account-name ccfperf --subscription $(subscription)
    workingDirectory: build

# cimetrics related tasks: render and publish results for Pull Requests build
- script: ./cimetrics_env.sh python -m cimetrics.plot
  env:
    METRICS_MONGO_CONNECTION: $(METRICS_MONGO_CONNECTION)
  workingDirectory: build
  displayName: 'Plot cimetrics'
  condition: eq(variables['Build.Reason'], 'PullRequest')

- script: ./cimetrics_env.sh python -m cimetrics.github_pr
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
  displayName: 'Post cimetrics graphs as PR comment'
  workingDirectory: build
  condition: eq(variables['Build.Reason'], 'PullRequest')

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: _cimetrics
    artifactName: cimetrics
  displayName: 'Publish cimetrics graphs as build artifact'
  condition: eq(variables['Build.Reason'], 'PullRequest')
